#include "ExtendedDataTypes.idl" // openrtm

module primitive_motion_level_msgs
{
  struct PrimitiveStateIdl
  {
    string name;
    string parentLinkName;
    RTC::Pose3D localPose;

    double time; // interpolation time
    RTC::Pose3D pose; // world frame
    sequence<double, 6> wrench; // world frame. around pose. robot receives
    sequence<double, 6> poseFollowGain;// pose local frame
    sequence<double, 6> wrenchFollowGain;// pose local frame

    // pose local frame (if isGlobal=false). world frame (if isGlobal=true).
    boolean isPoseCGlobal;
    sequence<sequence<double, 6> > poseC; //pose の frameからのerror の制約
    sequence<double> poseld;
    sequence<double> poseud;
    boolean isWrenchCGlobal;
    sequence<sequence<double, 6> > wrenchC; //wrench の制約
    sequence<double> wrenchld;
    sequence<double> wrenchud;

    // pose local frame
    sequence<double, 6> actWrench; // Position control only
    sequence<double, 6> M;
    sequence<double, 6> D;
    sequence<double, 6> K;

    // 支持脚かどうか
    boolean supportCOM;
  };

  struct TimedPrimitiveStateSeq
  {
    RTC::Time tm;
    sequence<PrimitiveStateIdl> data;
  };

  struct TimedPrimitiveStateSeqSeq
  {
    RTC::Time tm;
    sequence<TimedPrimitiveStateSeq> data; // 各要素のtmは一つ前の要素からの経過時間を表す
  };
};
